### ISSUE TITLE
Does GK constraints templatesconstraints can be used to validate /deny kubectl imperative cli commands?

### ISSUE THREAD

**Issue by clcchai** [open-policy-agent/gatekeeper-library#82] opened 2021-05-23 13:23 UTC
Unsure if GK  can be used to apply to imperative kubectl commands rather than just declaratively

**Comment by maxsmythe** [comment] 2021-05-26 00:50
Duplicate of https://github.com/open-policy-agent/gatekeeper/issues/1322

**Closed by maxsmythe** 2021-05-26 00:50 UTC
